// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDajGSyDexyRJyFZw1AtkqRd2RaLzm2GeM',
    appId: '1:573890276418:web:3d13bad9e3fe06c36e91db',
    messagingSenderId: '573890276418',
    projectId: 'medi-sync-plus',
    authDomain: 'medi-sync-plus.firebaseapp.com',
    storageBucket: 'medi-sync-plus.firebasestorage.app',
    measurementId: 'G-NQETTTZ1DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN9yPm1pTM6_-Dg9KSpY-GC3wrV8s62TE',
    appId: '1:573890276418:android:d7d857fe8685fd486e91db',
    messagingSenderId: '573890276418',
    projectId: 'medi-sync-plus',
    storageBucket: 'medi-sync-plus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCQoY57yoVwbqRK-sChaxTJ9AOHt9sT0g',
    appId: '1:573890276418:ios:6dfdef76d743b8376e91db',
    messagingSenderId: '573890276418',
    projectId: 'medi-sync-plus',
    storageBucket: 'medi-sync-plus.firebasestorage.app',
    iosBundleId: 'com.example.mediSyncPlusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCQoY57yoVwbqRK-sChaxTJ9AOHt9sT0g',
    appId: '1:573890276418:ios:6dfdef76d743b8376e91db',
    messagingSenderId: '573890276418',
    projectId: 'medi-sync-plus',
    storageBucket: 'medi-sync-plus.firebasestorage.app',
    iosBundleId: 'com.example.mediSyncPlusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDajGSyDexyRJyFZw1AtkqRd2RaLzm2GeM',
    appId: '1:573890276418:web:7955444fdbdf44be6e91db',
    messagingSenderId: '573890276418',
    projectId: 'medi-sync-plus',
    authDomain: 'medi-sync-plus.firebaseapp.com',
    storageBucket: 'medi-sync-plus.firebasestorage.app',
    measurementId: 'G-9X27BQ2YT5',
  );
}
